numpy:
  - 1.26
libprotobuf:
  - 5.28.2
protobuf:
  - 5.28.2
spdlog:
  - 1.14

cdt_name:
  - ${{ "cos7" if linux }}

python:
  - 3.11.* *_cpython
python_impl:
  - cpython

c_stdlib:
  - ${{ "sysroot" if linux }}
  - ${{ "macosx_deployment_target" if osx }}
  - ${{ "vs" if win }}
c_stdlib_version:
  - ${{ "2.17" if linux }}
  - ${{ "10.14" if osx and x86_64 }}
  - ${{ "11.0" if osx and arm64 }}
c_compiler:
  - ${{ "gcc" if linux }}
  - ${{ "clang" if osx }}
  - ${{ "vs2019" if win }}
cxx_compiler:
  - ${{ "gxx" if linux }}
  - ${{ "clangxx" if osx }}
  - ${{ "vs2019" if win }}
