gazebo:
  - '11'
libpqxx:
  - 7
numpy:
  - 1.23
ogre:
  - 14.2.*
setuptools:
  - 69
  
cdt_name:  # [linux]
  - cos7   # [linux]

python:
  - 3.12.* *_cpython
python_impl:
  - cpython

# # Project overrides
# macos_min_version:             # [osx and x86_64]
#   - 10.14                      # [osx and x86_64]
# macos_machine:                 # [osx]
#   - x86_64-apple-darwin13.4.0  # [osx and x86_64]
#   - arm64-apple-darwin20.0.0   # [osx and arm64]
# MACOSX_DEPLOYMENT_TARGET:      # [osx]
#   - 11.0                       # [osx and arm64]
#   - 10.14                      # [osx and x86_64]
# CONDA_BUILD_SYSROOT:
#   - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk  # [osx and arm64]