# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-ros2bag
  version: 0.26.8
source:
  git: https://github.com/ros2-gbp/rosbag2-release.git
  tag: release/jazzy/ros2bag/0.26.8-1
  target_directory: ros-jazzy-ros2bag/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_python.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_python.bat' }}
  number: 9
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pytest
    - python
    - ros-jazzy-ament-copyright
    - ros-jazzy-ament-flake8
    - ros-jazzy-ament-pep257
    - ros-jazzy-launch-testing
    - ros-jazzy-launch-testing-ros
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-rosbag2-storage-default-plugins
    - ros-jazzy-rosbag2-test-common
    - ros2-distro-mutex 0.10.* jazzy_*
    - setuptools
  run:
    - python
    - pyyaml
    - ros-jazzy-ament-index-python
    - ros-jazzy-rclpy
    - ros-jazzy-ros-workspace
    - ros-jazzy-ros2cli
    - ros-jazzy-rosbag2-py
    - ros2-distro-mutex 0.10.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
