# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-nav2-smac-planner
  version: 1.3.7
source:
  git: https://github.com/SteveMacenski/navigation2-release.git
  tag: release/jazzy/nav2_smac_planner/1.3.7-1
  target_directory: ros-jazzy-nav2-smac-planner/src/work
  patches:
    - patch/ros-jazzy-nav2-smac-planner.win.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 9
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - ${{ 'llvm-openmp' if osx }}
  host:
    - ${{ 'llvm-openmp' if osx }}
    - if: build_platform == target_platform
      then:
        - pkg-config
    - eigen
    - libode
    - nlohmann_json
    - numpy
    - ompl
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-ament-cmake-pytest
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-angles
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-nav2-common
    - ros-jazzy-nav2-core
    - ros-jazzy-nav2-costmap-2d
    - ros-jazzy-nav2-msgs
    - ros-jazzy-nav2-util
    - ros-jazzy-ompl
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2-ros
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.10.* jazzy_*
  run:
    - eigen
    - nlohmann_json
    - python
    - ros-jazzy-angles
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-nav-msgs
    - ros-jazzy-nav2-common
    - ros-jazzy-nav2-core
    - ros-jazzy-nav2-costmap-2d
    - ros-jazzy-nav2-msgs
    - ros-jazzy-nav2-util
    - ros-jazzy-ompl
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-rclcpp-lifecycle
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2-ros
    - ros-jazzy-visualization-msgs
    - ros2-distro-mutex 0.10.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
