# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-moveit-ros-move-group
  version: 2.12.3
source:
  git: https://github.com/ros2-gbp/moveit2-release.git
  tag: release/jazzy/moveit_ros_move_group/2.12.3-1
  target_directory: ros-jazzy-moveit-ros-move-group/src/work
  patches:
    - patch/ros-jazzy-moveit-ros-move-group.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 9
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - fmt
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-cmake-gtest
    - ros-jazzy-moveit-common
    - ros-jazzy-moveit-configs-utils
    - ros-jazzy-moveit-core
    - ros-jazzy-moveit-resources-fanuc-moveit-config
    - ros-jazzy-moveit-resources-panda-moveit-config
    - ros-jazzy-moveit-ros-occupancy-map-monitor
    - ros-jazzy-moveit-ros-planning
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-testing
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.10.* jazzy_*
  run:
    - fmt
    - python
    - ros-jazzy-moveit-common
    - ros-jazzy-moveit-core
    - ros-jazzy-moveit-kinematics
    - ros-jazzy-moveit-ros-occupancy-map-monitor
    - ros-jazzy-moveit-ros-planning
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-action
    - ros-jazzy-ros-workspace
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-geometry-msgs
    - ros-jazzy-tf2-ros
    - ros2-distro-mutex 0.10.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
