# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-ros2-controllers
  version: 4.28.0
source:
  git: https://github.com/ros2-gbp/ros2_controllers-release.git
  tag: release/jazzy/ros2_controllers/4.28.0-1
  target_directory: ros-jazzy-ros2-controllers/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 9
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros2-distro-mutex 0.10.* jazzy_*
  run:
    - python
    - ros-jazzy-ackermann-steering-controller
    - ros-jazzy-admittance-controller
    - ros-jazzy-bicycle-steering-controller
    - ros-jazzy-diff-drive-controller
    - ros-jazzy-effort-controllers
    - ros-jazzy-force-torque-sensor-broadcaster
    - ros-jazzy-forward-command-controller
    - ros-jazzy-gpio-controllers
    - ros-jazzy-gps-sensor-broadcaster
    - ros-jazzy-gripper-controllers
    - ros-jazzy-imu-sensor-broadcaster
    - ros-jazzy-joint-state-broadcaster
    - ros-jazzy-joint-trajectory-controller
    - ros-jazzy-mecanum-drive-controller
    - ros-jazzy-parallel-gripper-controller
    - ros-jazzy-pid-controller
    - ros-jazzy-pose-broadcaster
    - ros-jazzy-position-controllers
    - ros-jazzy-range-sensor-broadcaster
    - ros-jazzy-ros-workspace
    - ros-jazzy-steering-controllers-library
    - ros-jazzy-tricycle-controller
    - ros-jazzy-tricycle-steering-controller
    - ros-jazzy-velocity-controllers
    - ros2-distro-mutex 0.10.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
