# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-jazzy-orbbec-camera
  version: 1.5.13
source:
  git: https://github.com/JafarAbdi/orbbec-release.git
  tag: release/jazzy/orbbec_camera/1.5.13-1
  target_directory: ros-jazzy-orbbec-camera/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 9
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - elfutils
    - gflags
    - glog
    - nlohmann_json
    - numpy
    - pip
    - python
    - ros-jazzy-ament-cmake
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-backward-ros
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-camera-info-manager
    - ros-jazzy-cv-bridge
    - ros-jazzy-diagnostic-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-image-publisher
    - ros-jazzy-image-transport
    - ros-jazzy-orbbec-camera-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-statistics-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-tf2-sensor-msgs
    - ros2-distro-mutex 0.10.* jazzy_*
    - if: linux
      then:
        - libgl-devel
        - libopengl-devel
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
  run:
    - elfutils
    - gflags
    - glog
    - nlohmann_json
    - python
    - ros-jazzy-ament-index-cpp
    - ros-jazzy-ament-lint-auto
    - ros-jazzy-ament-lint-common
    - ros-jazzy-backward-ros
    - ros-jazzy-builtin-interfaces
    - ros-jazzy-camera-info-manager
    - ros-jazzy-cv-bridge
    - ros-jazzy-diagnostic-msgs
    - ros-jazzy-diagnostic-updater
    - ros-jazzy-image-publisher
    - ros-jazzy-image-transport
    - ros-jazzy-orbbec-camera-msgs
    - ros-jazzy-rclcpp
    - ros-jazzy-rclcpp-components
    - ros-jazzy-ros-workspace
    - ros-jazzy-sensor-msgs
    - ros-jazzy-statistics-msgs
    - ros-jazzy-std-msgs
    - ros-jazzy-std-srvs
    - ros-jazzy-tf2
    - ros-jazzy-tf2-eigen
    - ros-jazzy-tf2-msgs
    - ros-jazzy-tf2-ros
    - ros-jazzy-tf2-sensor-msgs
    - ros2-distro-mutex 0.10.* jazzy_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - if: unix
      then:
        - xorg-libx11
        - xorg-libxext
